# Generated by Django 4.1 on 2022-09-17 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('regno', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=50)),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Bio-Diesel', 'Bio-Diesel')], max_length=50)),
                ('colour', models.CharField(max_length=15)),
                ('expdate', models.DateField(blank=True)),
                ('delivery', models.CharField(choices=[('Delivery Type', 'Delivery Type'), ('Pickup Service', 'Pickup Service'), ('Drop Service', 'Drop Service')], max_length=50)),
                ('servdate', models.DateField(blank=True)),
                ('pickdate', models.DateField(blank=True)),
                ('serv', models.CharField(choices=[('General Service', 'General Service'), ('Fuel Service', 'Fuel Service'), ('Interim Service', 'Interim Service'), ('Battery Check and Service', 'Battery Check and Service'), ('Full Car Service', 'Full Car Service'), ('Denting and Painting', 'Denting and Painting'), ('Major Car Service', 'Major Car Service'), ('Accidental Repairs', 'Accidental Repairs')], max_length=50)),
                ('oth', models.CharField(choices=[('Tyre Replace', 'Tyre Replace'), ('Sparkplug, Clutch and Brake Service', 'Sparkplug, Clutch and Brake Service'), ('Windshield Replace', 'Windshield Replace'), ('Engine Replace', 'Engine Replace'), ('AC service and Replace', 'AC service and Replace'), ('Car Wash', 'Car Wash'), ('Interior Cleaning', 'Interior Cleaning'), ('Car Heater Service', 'Car Heater Service'), ('Oil Replace', 'Oil Replace'), ('Other/Custom Service', 'Other/Custom Service')], max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
