# Generated by Django 4.1 on 2022-09-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm_app1', '0002_remove_registration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(choices=[('Bengaluru', 'Bengaluru'), ('Dharwad', 'Dharwad'), ('Hubballi', 'Hubballi'), ('Bagalkot', 'Bagalkot'), ('Ballari', 'Ballari'), ('Chikkaballapur', 'Chikkaballapur'), ('Davanagere', 'Davanagere'), ('Gadag', 'Gadag'), ('Gulbarga', 'Gulbarga'), ('Hassan', 'Hassan'), ('Haveri', 'Haveri'), ('Hospet', 'Hospet'), ('Koppal', 'Koppal'), ('Mysore', 'Mysore'), ('Mysore', 'Mysore'), ('Raichur', 'Raichur'), ('Shimoga', 'Shimoga'), ('Udupi', 'Udupi'), ('Yellapur', 'Yellapur')], max_length=100),
        ),
    ]
